* Made some fixes so you can choose your own prefix path and choose gcc-version

diff --git a/toolchain-morphos b/toolchain-morphos
--- a/toolchain-morphos
+++ b/toolchain-morphos
@@ -1,27 +1,137 @@
-#!/bin/sh
+#!/bin/bash
 #
-# setup-cross-env.sh version 1.3 Copyright 2013-2015 Mark Olsen
+# setup-cross-env.sh version 1.5 Copyright 2013-2016 Mark Olsen, 2017 Marlon Beijer
 #
 # Script to automatically set up a MorphOS cross compiler environment on Linux (and other Unix-oids).
 #
 # History:
+# 1.5 - 20171212
+#  - Made it so you can choose which gcc-version to use, and which prefix to install in.
+#	Marlon Beijer
+#
 # 1.4 - 20160129
 #  - The GNU people just can't stop breaking Makeinfo, so documentation generation for GCC is now disabled to avoid Makeinfo problems.
 #  - The GNU people also just can't stop breaking GCC, so a patch to let GCC build with (a newer) GCC has also been included.
+#	Mark Olsen
 #
 # 1.3 - 20150812
 #  - Now works on Mac OS X
+#	Mark Olsen
 #
 
-VERSION='20160605'
+VER='1.5'
+SDKVERSION='20160605'
 PREFIX='/opt/ppc-morphos'
+GCCVER='gcc5'
+gccarray=("gcc4\tgcc5")
 
-wget http://www.morphos-team.net/files/sdk-$VERSION.lha
-wget http://www.morphos-team.net/files/src/sdk/sdk-source-$VERSION.tar.xz
+usage () {
+	printf "MorphOS Cross Toolchain v$VER\n"
+	printf "Usage: $0 [OPTION]...\n\n"
+	printf "Options:\n"
+	printf "  -p,  --prefix\t\tchoose the path for your prefix. Default: $PREFIX\n"
+	printf "  -g,  --gcc\t\tpick the version of gcc you want to install. Available versions: gcc4, gcc5 (default)\n"
+	printf "  -v,  --version\t\tdisplay the SDK-version of MorphOS and exit\n"
+	printf "  -h,  --help\t\t\tprint this help\n"
+	printf "\n"
+	exit 1;
+}
 
-if [ "$1" = "--force" ]
+# Picking GCC version
+gcchelp () { printf "Available GCC versions:\n * gcc4\n * gcc5 (default)\n"; }
+
+pickgcc () {
+	if [ -z "$1" ]; then
+		gcchelp;
+		exit 1;
+	else
+		if [[ "\t${gccarray[@]}\t" =~ "\t${1}\t" ]]; then
+			GCCVER=$1;
+		else
+			gcchelp;
+			exit 1;
+		fi
+	fi
+}
+
+prefixhelp () { printf "Usage: $0 --prefix /path/to/prefix\n"; }
+
+pickprefix () {
+	if [ -z "$1" ]; then
+		prefixhelp;
+		exit 1;
+	else
+		PREFIX=$1;
+	fi
+}
+
+
+ARGV0=$0 # First argument is shell command (as in C)
+
+ARGC=$#  # Number of args, not counting $0
+
+i=1  # Used as argument index
+while [ $i -le $ARGC ]; do
+	case ${!i} in
+		"--version")
+			printf "Using SDK version: $SDKVERSION.\n"
+			exit 1;
+			;;
+		"-v")
+			printf "Using SDK version: $SDKVERSION.\n"
+			exit 1;
+			;;
+		"--prefix")
+			i=$((i+1))
+			pickprefix ${!i}
+			;;
+		"-p")
+			i=$((i+1))
+			pickprefix ${!i}
+			;;
+		"--gcc")
+			i=$((i+1))
+			pickgcc ${!i}
+			;;
+		"-g")
+			i=$((i+1))
+			pickgcc ${!i}
+			;;
+		"-h")
+			usage
+			exit 1
+			;;
+		"-f")
+			FORCE=y
+			;;
+		"--force")
+			FORCE=y
+			;;
+		"--help")
+			usage
+			exit 1
+			;;
+	esac
+	i=$((i+1))
+done
+
+for i in bison bzip2 flex gcc-5 ld lha m4 make makeinfo patch xz wget
+do
+	if [ -z "`which $i`" ]
+	then
+		echo "$i is missing."
+		ERROR=1
+	fi
+done
+
+if [ ! -f "sdk-$SDKVERSION.lha" ]
 then
-	FORCE=y
+	wget http://www.morphos-team.net/files/sdk-$SDKVERSION.lha -O sdk-$SDKVERSION.lha
+fi
+
+if [ ! -f "sdk-$SDKVERSION.lha" ]
+then
+	wget http://www.morphos-team.net/files/src/sdk/sdk-source-$SDKVERSION.tar.xz -O sdk-source-$SDKVERSION.tar.xz
 fi
 
 if [ ! -d $PREFIX ]
@@ -48,20 +158,11 @@ then
 	ERROR=1
 fi
 
-for i in bison bzip2 flex gcc ld lha m4 make makeinfo patch xz
-do
-	if [ -z "`which $i`" ]
-	then
-		echo "$i is missing."
-		ERROR=1
-	fi
-done
-
 if [ -z "$FORCE" ]
 then
 	if [ -d $PREFIX/include ] || [ -d $PREFIX/os-include ] || [ -d $PREFIX/includestd ] || [ -d $PREFIX/ppc-morphos ]
 	then
-		echo "You already have an SDK installed in $PREFIX. Either remove the old SDK manually or use --force to automatically overwrite it."
+		echo "You already have an SDK installed in $PREFIX. Either remove the old SDK manually or use -f/--force to automatically overwrite it."
 		ERROR=1
 	fi
 fi
@@ -91,6 +192,8 @@ then
 fi
 
 echo "Using SDK version: $SDKVERSION."
+echo "Installing in prefix: $PREFIX"
+echo "Chosen GCC version: $GCCVER"
 
 if [ "`uname`" = "Darwin" ]
 then
@@ -106,7 +209,7 @@ then
 	exit 1
 fi
 
-trap "rm -rf \"$TMPDIR\"" exit
+#trap "rm -rf \"$TMPDIR\"" exit
 
 if [ -d $PREFIX/include ] || [ -d $PREFIX/os-include ] || [ -d $PREFIX/includestd ] || [ -d $PREFIX/ppc-morphos ]
 then
@@ -120,12 +223,14 @@ echo "Extracting SDK files."
 (cd "$TMPDIR" && lha -x "$CURDIR/$SDK" "morphossdk/sdk.pack" >/dev/null && xz -dcf morphossdk/sdk.pack | (cd $PREFIX && tar --transform "s,^Development/GG/,," -x "Development/GG/ppc-morphos" "Development/GG/include" "Development/GG/includestd" "Development/GG/os-include")) || exit 1
 
 # Extract the Binutils/GCC source code.
-(cd "$TMPDIR" && tar -xf "$CURDIR/$SDKSOURCE" binutils gcc4)
+(cd "$TMPDIR" && tar -xf "$CURDIR/$SDKSOURCE" binutils $GCCVER)
 
 # Build Binutils
 echo "Building binutils."
 cd "$TMPDIR" && chmod -R 777 binutils
+
 # Fortify on Ubuntu, which is enabled by default, detects phantom errors which according to Valgrind don't exist. Adding -U_FORTIFY_SOURCE to avoid this.
+(cd "$TMPDIR/binutils" && sed -i 's|s/@prefix@/\\/gg/|s\|@prefix@\|'$PREFIX'\||g' configall 2>&1) || ERROR=1
 (cd "$TMPDIR/binutils" && CFLAGS="-m32 -O2 -U_FORTIFY_SOURCE" ./configall >"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
 
 # Are we Mac OS X? Apply some dubious patches to try to get this to build...
@@ -137,9 +242,9 @@ then
 --- libiberty.h.orig    2015-06-19 16:07:57.000000000 +0300
 +++ libiberty.h 2015-08-12 20:56:54.000000000 +0300
 @@ -108,7 +108,7 @@
- 
+
  /* Exit, calling all the functions registered with xatexit.  */
- 
+
 -#ifndef __GNUC__
 +#ifndef __NOTREALLYGNUC__
  extern void xexit PARAMS ((int status));
@@ -151,13 +256,13 @@ EOF
 --- strerror.c.orig     2015-06-19 16:07:59.000000000 +0300
 +++ strerror.c  2015-08-12 20:59:35.000000000 +0300
 @@ -466,7 +466,7 @@
- 
+
  #else
- 
+
 -extern int sys_nerr;
 +extern const int sys_nerr;
  extern char *sys_errlist[];
- 
+
  #endif
 EOF
 
@@ -182,7 +287,10 @@ do
 done
 
 # Build GCC 4
-echo "Building GCC 4."
+echo "Building $GCCVER."
+
+if [ $GCCVER == "gcc4" ]
+then
 
 test -z "$ERROR" && (cd "$TMPDIR/gcc4" && make gcc4_unpack >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
 
@@ -235,21 +343,31 @@ fi
  #  define CTZ_HWI __builtin_ctzl
 EOF
 
-test -z "$ERROR" && (cd "$TMPDIR/gcc4" && sed "s,../configure --target=ppc-morphos.*$,& MAKEINFO=missing," <Makefile >Makefile.new && mv Makefile.new Makefile) || ERROR=1
+	test -z "$ERROR" && (cd "$TMPDIR/gcc4" && sed "s,../configure --target=ppc-morphos.*$,& MAKEINFO=missing," <Makefile >Makefile.new && mv Makefile.new Makefile) || ERROR=1
 
-test -z "$ERROR" && (cd "$TMPDIR/gcc4" && make >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
-test -z "$ERROR" && (cd "$TMPDIR/gcc4" && make install >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
+	test -z "$ERROR" && (cd "$TMPDIR/gcc4" && make >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
+	test -z "$ERROR" && (cd "$TMPDIR/gcc4" && make install >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
+
+	# Set up some GCC symlinks
+	ln -sf $PREFIX/bin/ppc-morphos-gcc-4 $PREFIX/bin/ppc-morphos-gcc
+	ln -sf $PREFIX/bin/ppc-morphos-g++-4 $PREFIX/bin/ppc-morphos-g++
+else
+	cd "$TMPDIR/gcc5"
+	sed -i "s|/gg|$PREFIX|g" Makefile
+	test -z "$ERROR" && (cd "$TMPDIR/gcc5" && make >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
+	test -z "$ERROR" && (cd "$TMPDIR/gcc5" && make install >>"$CURDIR/setup-cross-sdk.log" 2>&1) || ERROR=1
+
+	# Set up some GCC symlinks
+	ln -sf $PREFIX/bin/ppc-morphos-gcc-5 $PREFIX/bin/ppc-morphos-gcc
+	ln -sf $PREFIX/bin/ppc-morphos-g++-5 $PREFIX/bin/ppc-morphos-g++
+fi
 
 if [ ! -z "$ERROR" ]
 then
-	echo "Failed to build GCC 4 for whatever reason. You're unfortunately on"
+	echo "Failed to build $GCCVER for whatever reason. You're unfortunately on"
 	echo "your own now. Check \"$CURDIR/setup-cross-sdk.log\" for details."
 	exit 1
 fi
-
-# Set up some GCC symlinks
-ln -s $PREFIX/bin/ppc-morphos-gcc-4 $PREFIX/bin/ppc-morphos-gcc
-ln -s $PREFIX/bin/ppc-morphos-g++-4 $PREFIX/bin/ppc-morphos-g++
 
 echo 'All done!'
 
